name: "run-tests"
description: "run-tests"


runs:
  using: "composite"
  steps:

    - name: Install Dependencies
      shell: bash
      run: |          
        pip install -r requirements-test.txt

    - name: Run Unit Tests (Unit)
      shell: bash
      run: |
        coverage run --source=mgraph_ai -m pytest -v -s --durations=0 tests/unit